name: Auto Dependency Bot
on:
  schedule:
    - cron: '0 21 * * *'  # UTC 19:00 = KST 06:00
  workflow_dispatch:

jobs:
  dispatch:
    uses: rbln-sw/optimum-rbln/.github/workflows/auto_dependency_bot_impl.yml@dev
    secrets: inherit
